# Generated by Django 5.2 on 2025-07-07 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_option_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
